### ISSUE TITLE
[bug] failed to `make build-cli` to build pouch cli

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#2845]
### Ⅰ. Issue Description

I found that recently the [pouchrobot](https://github.com/pouchcontainer/pouchrobot) failed to generate cli docs automatically.

Please see the failure log. It seems to be related with buildkit code which is introduced in https://github.com/alibaba/pouch/pull/2779.

```
root@7a95dc252894:/go/src/github.com/alibaba/pouch# make build-cli
build-cli: bin/pouch
# github.com/alibaba/pouch/vendor/github.com/moby/buildkit/util/apicaps
vendor/github.com/moby/buildkit/util/apicaps/caps.go:147:8: undefined: strings.Builder
Makefile:125: recipe for target 'build-cli' failed
make: *** [build-cli] Error 2
root@7a95dc252894:/go/src/github.com/alibaba/pouch# git log
commit 5c253f937da2bfb4cd030d81800ecf1145805896
Author: Rudy Zhang <rudyflyzhang@gmail.com>
Date:   Mon May 13 14:22:22 2019 +0800

    remove useless break statement

    Signed-off-by: Rudy Zhang <rudyflyzhang@gmail.com>

commit 2596dc7bc81e7fff6ffa481c0decb53ddb2b036d
```

### Ⅱ. Describe what happened

`make build-cli` failed.

### Ⅲ. Describe what you expected to happen
`make build-cli` works

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

see the command line display above.

### Ⅴ. Anything else we need to know?
none

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fuweid** [comment]
@allencloud the `strings.Builder` is introduced in go1.10 https://golang.org/doc/go1.10#strings . Please update your golang version. Thanks
